### ISSUE TITLE
Change the links colors?

### ISSUE THREAD

**Issue by MightyCreak** [MightyCreak/mesamatrix#100]
Hi!

I've received one email about the new colors of the links. He/she didn't like them.
If you share his/her opinion, please tell me here and, even better, you can propose some colors for the link and visited colors ;)

Cheers!

**Comment by Xenopathic** [comment]
I think the browser-defined link colours are best to use, since they are consistent across all websites and the blue/purple colours are well-understood by users. However, I do like the text decoration changes (removing the underline unless hovered over)

**Comment by MightyCreak** [comment]
That's basically what the email was saying too.

I tried to take the colors from the Mesamatrix logo and I liked the idea of graying out the links that you already visited (I find it more instinctive than purple).

Just saying this to explain why the changes, but honestly, I'm really OK to change them back (it was especially the text decoration that was bugging me ;))

**Comment by MightyCreak** [comment]
Since most of the website override these colors, I'll keep them as they are right now. If I find a better choice of colors, or if someone comes with a PR with better colors, I'll change them.

In the meantime, since this issue didn't drag much attention, I'll close it.
