### ISSUE TITLE
freedreno support?

### ISSUE THREAD

**Issue by shmerl** [MightyCreak/mesamatrix#104]
Do you plan to add a column for freedreno driver?

**Comment by MightyCreak** [comment]
I'd like to, but it's impossible right now, [GL3.txt](https://cgit.freedesktop.org/mesa/mesa/tree/docs/GL3.txt) doesn't expose this information.

**Comment by shmerl** [comment]
May be I can file a feature request to Mesa bug tracker to add that info there.

**Comment by shmerl** [comment]
See https://bugs.freedesktop.org/show_bug.cgi?id=95460

**Comment by MightyCreak** [comment]
The mesa devs are a bit reluctant to add stuff in this file for an external app (like Mesamatrix), but for sure it would be nice if it was accepted! ;)

**Comment by shmerl** [comment]
Rob Clark provided an update there. Hopefully they'll integrate it and will keep it up to date too.

**Comment by MightyCreak** [comment]
That's really cool! Can you keep me posted if the commit gets its way into master?

**Comment by shmerl** [comment]
I'll update you here if any commits will happen in that upstream bug.

**Comment by MightyCreak** [comment]
Excellent! Thanks!

**Comment by shmerl** [comment]
So far Mesa maintainers didn't reply anything to that [feature request](https://bugs.freedesktop.org/show_bug.cgi?id=95460), not sure, may be they don't think it's useful for anyone? May be you can chime in there, as developer of Mesa Matrix, to point out that it's useful for you?

**Comment by MightyCreak** [comment]
I'll see what I can do, but Mesa devs aren't _all_ very happy about Mesamatrix. Some thinks that features.txt is merely for the mesa devs so they can organize their work, and it's not meant for public exposure like Mesamatrix does. But some doesn't.

**Comment by MightyCreak** [comment]
patch rebased: https://bugs.freedesktop.org/show_bug.cgi?id=95460
mails sent: https://lists.freedesktop.org/archives/mesa-dev/2016-December/139102.html

now we wait... ;)

**Comment by Tele42** [comment]
Per https://cgit.freedesktop.org/mesa/mesa/commit/?id=8d8ed437a5f15a7a3e843cfe8d5b66be918680d9, data is now available.

**Comment by MightyCreak** [comment]
Yep, it's even displayed in https://mesamatrix.net !

Just forgot to close this issue ;)
Fixed with 0a712e7bacc9711200404f7fb9b280815d3bd07f
