### ISSUE TITLE
Extensions not part of any GL or GL ES version support

### ISSUE THREAD

**Issue by Tankypon** [MightyCreak/mesamatrix#105]
Hey recently Ian Romanick post a [commit](https://cgit.freedesktop.org/mesa/mesa/commit/?id=6bc54911939e75245d94aed3b40082587c3b74b4) in which we can find all the extensions not part of any GL or GL ES version. Maybe it would be nice to display them on Mesamatrix, what do you think?

**Comment by MightyCreak** [comment]
I agree, I'll have to find a way to parse that since it's a bit different from the other sections ;)
