### ISSUE TITLE
GL3.txt has moved

### ISSUE THREAD

**Issue by Tele42** [MightyCreak/mesamatrix#107]
G'day,

As of https://cgit.freedesktop.org/mesa/mesa/commit/?id=f926cf5bd0ade3273b320ca4483d826fcfe20bbb GL3.txt has moved to features.txt which should have broken the primary parser.

**Comment by MightyCreak** [comment]
Hey!

Thank you for noticing me. This will require a bit of code; I don't know how git handles file renaming, I guess it's just considered as a whole new file.

I'll get to that ASAP since it's clearly a major offender.

**Comment by MightyCreak** [comment]
If someone wants to check this CL (@Xenopathic, maybe?). To fix the issue, I fetch the commits for `GL3.txt` and then the commits for `features.txt` in one array, and then search for successive duplicates and remove the first of them.

The reason why I do that is that the first entry (in the successive duplicates) is the commit saying that the file has been moved to `/dev/null` while the second entry is the creation of `docs/features.txt`.
