### ISSUE TITLE
Intel GLES 3.1 ARB_stencil_texturing parsing anomaly

### ISSUE THREAD

**Issue by Tele42** [MightyCreak/mesamatrix#109]
I have yet another edge case to investigate. As of the writing of this issue report, ARB_stencil_texturing in GLES 3.1 for Intel is parsed as Gen 8+, but features.txt reports haswell (Gen 7.5)+. As a side note, this is the last extension blocking Gen 7 from supporting GLES 3.1 and Intel will become easier to parse if/when that gains support.

**Comment by MightyCreak** [comment]
Good catch. It must be the merging of the history that fails on the special `/gen8+` and `/hsw+` syntax.

The bug would probably hide somewhere in https://github.com/MightyCreak/mesamatrix/blob/master/lib/Console/Command/Parse.php in `generateMergedXml()`.

Do you think you would be able to look at that?

**Comment by Unaccounted4** [comment]
I have a Gen7 Ivy Bridge laptop (i3 4005U) and GL_ARB_stencil_texturing is working properly.

**Comment by MightyCreak** [comment]
I think it's been definitely fixed with @floriankisser's commits d28fe1992199b0dffb5caa79c9d094a4e3cf1701 and 7f8f16024daf67449f8bb911e79857a041bb804e :+1:
