### ISSUE TITLE
GL_OES_tessellation_shader doesn't show proper support

### ISSUE THREAD

**Issue by Mystro256** [MightyCreak/mesamatrix#111]
The note says "all drivers that support GL_ARB_tessellation_shader" for GL_OES_tessellation_shader from this commit:

https://cgit.freedesktop.org/mesa/mesa/commit/?id=049cee2c164dda219d2c4803dcb5c64fb5ad2b4c

So, I guess it only thinks mesa supports it, but in reality, it should be i965/gen7+, nvc0, radeonsi, r600.

**Comment by MightyCreak** [comment]
Hi!

It's actually much more than this extension, it's about all the extension that has "all drivers that support" in their comment and it needs to add a layer of dependencies between the extension which isn't there yet :/

There is already a bug for that (#95) so I'll have to close this one.

Thanks!

**Comment by Mystro256** [comment]
Nice, thanks!
