### ISSUE TITLE
GL_OES_tessellation_shader is marked as done for core only

### ISSUE THREAD

**Issue by 375gnu** [MightyCreak/mesamatrix#112]
GL_OES_tessellation_shader is marked as done for core only, while txt says "all drivers that support GL_ARB_tessellation_shader", i.e. i965/gen7+, nvc0, radeonsi.

**Comment by MightyCreak** [comment]
Hi!

It's actually much more than this extension, it's about all the extension that has "all drivers that support" in their comment and it needs to add a layer of dependencies between the extension which isn't there yet :/

There is already a bug for that (#95) so I'll have to close this one.

Thanks!

**Comment by MightyCreak** [comment]
Duplicate #95

**Comment by MightyCreak** [comment]
Fixed by 8841654
