### ISSUE TITLE
Radeonsi GL_ARB_enhanced_layouts is wrong

### ISSUE THREAD

**Issue by Mystro256** [MightyCreak/mesamatrix#117]
According to features.txt, radeonsi has finished 4.4 but still says it's only 4.3.

_GL_ARB_enhanced_layouts_ was just finished, but it only says _DONE (i965, llvmpipe, softpipe)_

I'm assuming that the line "_GL 4.4, GLSL 4.40 -- all DONE: i965/gen8+, radeonsi_" doesn't override this.

See commit:
https://cgit.freedesktop.org/mesa/mesa/commit/?id=789119d21212da3891ed57018ec1af197a48977c

**Comment by MightyCreak** [comment]
It should override it, but there must be a bug with the drivers merging in the sub-extension

**Comment by Mystro256** [comment]
It seems that both nv50 and nvc0 are working, this only affects radeonsi

**Comment by gnarlin** [comment]
Maybe you should manually green out those fields until the parsing bug is fixed?

**Comment by floriankisser** [comment]
Revert the commit in mesa until mesamatrix is fixed? :)

**Comment by MightyCreak** [comment]
I was in holidays, sorry ;)

Indeed it works with nvc0, which makes it very strange. I'll dig into that as soon as I've got a bit of time for me, but you can try to debug too if you want.

**Comment by Mystro256** [comment]
Wild guess: Nvc0 wasn't affected because of this commit:
https://cgit.freedesktop.org/mesa/mesa/commit/?id=afb6dc53bff58c137d07ca5b58c50debce5729d8
which was then "cleaned up" by this commit:
https://cgit.freedesktop.org/mesa/mesa/commit/?id=5f885225cf90aa58b2900355658441bda618e9b1

Perhaps the "gen8+" is messing things up? Is it comma delimited? Something like a split?

**Comment by MightyCreak** [comment]
Nice catch! I think I know where the problem lies, it's both with the sub-extensions and when the merging needs to *remove* a status instead of adding one.

**Comment by floriankisser** [comment]
Actually it's much simpler than that ^^
