### ISSUE TITLE
Parsing error concerning Extensions not part of any GL or GL ES version

### ISSUE THREAD

**Issue by Jiray** [MightyCreak/mesamatrix#119]
The section "Khronos, ARB, and OES extensions that are not part of any OpenGL or OpenGL ES version[,]" for which support was added in #105, is currently marked as complete for Intel hardware.
Most likely the responsible commit is the following, which marks all extensions from OpenGL ES 3.2 as complete for this hardware.
https://cgit.freedesktop.org/mesa/mesa/commit/docs/features.txt?id=6c648cdac80233765861bfebb74a6e2725ddbf26
![screenshot from 2016-10-16 18-46-01](https://cloud.githubusercontent.com/assets/6448982/19419161/dc9fe910-93d1-11e6-83d7-2281790ecc97.png)

**Comment by floriankisser** [comment]
Already fixed in #118 ;)

**Comment by Jiray** [comment]
Nice, then this issue can be closed.
