### ISSUE TITLE
EGL support

### ISSUE THREAD

**Issue by urzds** [MightyCreak/mesamatrix#121]
It would be great if you could also list EGL + extension support by driver.

**Comment by MightyCreak** [comment]
I can only display the data inside [features.txt](https://cgit.freedesktop.org/mesa/mesa/tree/docs/features.txt). Only the mes devs can add more data to this file, so in order to have the EGL extensions status, it has to be asked to the mesa devs.

Cheers! ;)

**Comment by urzds** [comment]
See-Also: https://bugs.freedesktop.org/show_bug.cgi?id=104478
