### ISSUE TITLE
Intel driver hsw is not 4.5?

### ISSUE THREAD

**Issue by jose-antonio-escobar** [MightyCreak/mesamatrix#122]
In features.txt appears:
GL 4.3, GLSL 4.30 -- all DONE: i965/gen8+, nvc0, radeonsi
GL 4.4, GLSL 4.40 -- all DONE: i965/gen8+, nvc0, radeonsi
GL 4.5, GLSL 4.50 -- all DONE: nvc0, radeonsi

But in the table appears as if haswell is already 4.5

Why they are not in agreement?

**Comment by MightyCreak** [comment]
I'd like to be able to display this kind of information, but it's a bit harder to show in the table. The other drivers don't have (or don't show) which GPU generations are supported, per extension, so the table is pretty much relevant for them. On the other hand, Intel has only one driver, but the drivers supports OpenGL at different levels, which is the hard part to follow when trying to sum it up in the table.

If I can parse these information, I could maybe display a tooltip specifying exactly which OpenGL version is supported by which Intel's GPU gen...

**Comment by mirh** [comment]
https://github.com/mesa3d/mesa/blob/master/src/mesa/drivers/dri/i965/intel_extensions.c

Also, even r600 spawns across many generations (as discussed in #12)
Which I think has the right info [here](https://github.com/mesa3d/mesa/blob/master/src/gallium/drivers/r600/r600_pipe.c). 
Not sure about nvidia, but it would seem unlikely this wasn't the case for them.
