### ISSUE TITLE
Some fields are unreadable

### ISSUE THREAD

**Issue by cristim** [MightyCreak/mesamatrix#127]
The date field is sometimes word-wrapped to the next line because the columns are too narrow, as seen in the screenshot below:

![image](https://user-images.githubusercontent.com/95209/29750144-bd42c48c-8b3a-11e7-9877-94504efd2882.png)

Those columns should be extended and made wide enough to contain all the date fields.

**Comment by MightyCreak** [comment]
Thanks for the feedback!

It's like the CSS for the dates aren't applied in your browser, could you tell me how did you get that (which browser, version, OS, etc.)?

**Comment by cristim** [comment]
It's Chromium 60.0.3112.78, running on Ubuntu 17.04, x86_64.
I confirm it looks better in Firefox on the same machine, so it must be some browser-specific thing.

I thought the times when web development was all about fixing browser-specific bugs are over but it seems we're not there yet...

**Comment by cristim** [comment]
It seems with zoom 125% it looks decent also in Chromium:

![image](https://user-images.githubusercontent.com/95209/29751307-95e5e7c8-8b4b-11e7-81c7-5d0a9360dd6c.png)

**Comment by qwertychouskie** [comment]
This no longer seems to be an issue:

![image](https://user-images.githubusercontent.com/13989090/34897891-47ad75e6-f7a5-11e7-9102-fc2c96728300.png)

Chromium Version 63.0.3239.84 (Official Build) Built on Ubuntu , running on Ubuntu 17.10 (64-bit)

**Comment by MightyCreak** [comment]
Cool! I like these bugs that auto-fix themselves ;)
