### ISSUE TITLE
Extension: gpu_shader4 ?

### ISSUE THREAD

**Issue by ax3l** [MightyCreak/mesamatrix#128]
Hi,

thank you for the great list!

I was looking for an extension which is named in GLEW as `GLEW_EXT_gpu_shader4` and is required by recent versions of [VTK](https://github.com/Kitware/VTK/blob/v7.1.1/Rendering/OpenGL2/vtkOpenGLRenderWindow.cxx#L632-L648) for its OpenGL2 backend.

Is there such an extension and can its implementation status be added to the matrix?

My background: I was trying to use mesa 17.1.5 with llvmpipe driver (based on llvm 3.8.1) and was surprised that VTK7 failed (in ParaView 5.4.1) to detect all required OpenGL 3.2 features.

cc @robertmaynard

P.S. the official naming seems to be [`GL_EXT_gpu_shader4`](https://github.com/Kitware/VTK/blob/v7.1.1/Rendering/OpenGL2/vtkOpenGLShaderCache.cxx#L172-L214) (as part of fragment shaders?)

Kronos document: https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_gpu_shader4.txt

**Comment by MightyCreak** [comment]
Hello!

Mesamatrix is simply parsing the mesa feature listing file here:
https://cgit.freedesktop.org/mesa/mesa/tree/docs/features.txt

I have seen `GL_ARB_gpu_shader5` in the list (OpenGL 4.0), but no `GL_ARB_gpu_shader4`. You should ask the mesa mailing list, the devs would give you a way better explanations than mine 😄

**Comment by ax3l** [comment]
Thank you for the quick answer! :)

I did as you recommended and forwarded the question to the mesa (users) list: https://lists.freedesktop.org/archives/mesa-users/2017-October/001377.html 😄

**Comment by ax3l** [comment]
[List feedback](https://lists.freedesktop.org/archives/mesa-users/2017-October/001380.html) on that extension:

> shader4 is not in mesa and I do not think it ever will be. As Mesa has
opengl 3.2 support it really isn't needed for VTK/PV because OpenGL 3.2
basically includes the features of shader4.

my VTK / ParaView issue seems to be more related that (see link under `VTK` in PR description) my mesa build somehow did not fully expose its OpenGL 3.1/3.2 features in `if (!GLEW_VERSION_3_2 && !GLEW_VERSION_3_1)`.

**Comment by MightyCreak** [comment]
Good to know! Thank you!

**Comment by mirh** [comment]
https://github.com/mesa3d/mesa/blob/master/src/mesa/state_tracker/st_extensions.c

shader4 is available since this spring.

**Comment by ax3l** [comment]
Oh cool, thanks for the update! :100:
