### ISSUE TITLE
R600 commit.. Changed freedreno?

### ISSUE THREAD

**Issue by mirh** [MightyCreak/mesamatrix#133]
https://patchwork.freedesktop.org/patch/198579/
Nothing about freedreno is touched, yet mesamatrix reports it's now enabled there too.

**Comment by MightyCreak** [comment]
Freedreno has been changed because now `- specified vec4-slot component numbers` is flagged as completely done:

```diff
-  - specified vec4-slot component numbers               DONE (i965, nv50, llvmpipe, softpipe)
+  - specified vec4-slot component numbers               DONE```

I don't know if it was David Airlie's intention though.

**Comment by mirh** [comment]
Oh, I see you are right. Totally makes sense.
