### ISSUE TITLE
HTTPS error on mesamatrix.net due to expired certificate

### ISSUE THREAD

**Issue by Calinou** [MightyCreak/mesamatrix#134]
Visiting [Mesamatrix](https://mesamatrix.net/) currently causes this error due to an expired TLS certificate:

**Firefox:**

![screenshot_20180120_021214](https://user-images.githubusercontent.com/180032/35178262-6acc8c50-fd87-11e7-8478-9a6189825bec.png)

**Chromium:**

![screenshot_20180120_021236](https://user-images.githubusercontent.com/180032/35178263-6aeca1ac-fd87-11e7-96dd-ed3770988ab4.png)

**Comment by MightyCreak** [comment]
I'm on it, there must be a problem with the renewal script.

**Comment by MightyCreak** [comment]
Fixed!
