### ISSUE TITLE
please add virgl support

### ISSUE THREAD

**Issue by airlied** [MightyCreak/mesamatrix#139]
I've pushed virgl support to the features.txt please add support to the website.

**Comment by shmerl** [comment]
Thanks, that finally properly closes https://bugs.freedesktop.org/show_bug.cgi?id=95460

**Comment by MightyCreak** [comment]
Will do as soon as I can! (as explained on Phoronix, I'm on vacation in another country right now, so it might take some days before I get it done).

**Comment by MightyCreak** [comment]
Well it was way easier than expected, so it's done with commit cd06155bb9310cc5fafb7e0c5bd8003f66b33911
