### ISSUE TITLE
On-hover pilcrow links cause layout jitter in the Vulkan section

### ISSUE THREAD

**Issue by ssokolow** [MightyCreak/mesamatrix#140]
As the mouse crosses the longest rows in the "Extensions that are not part of any Vulkan version" table, the appearance of the permalink pilcrow causes the column widths to change.

![screenshot2](https://user-images.githubusercontent.com/46915/41804621-da6570f0-7667-11e8-8e7f-91a8dac15873.png)

This is a common issue with using `display: none` to implement these sorts of links and the usual solution is to use `visibility: hidden` instead, so that the space remains reserved even when the pilcrow is invisible and no re-layout takes place when it's toggled.

**Comment by MightyCreak** [comment]
Fixed with c314973f88dadcf78c9a573a3cc017cf2dacb914

Thanks for the tip!
