### ISSUE TITLE
Mesa commit 9fd3dff9082c6f6837c36a9afadb29eadf84d44b wasn't parsed

### ISSUE THREAD

**Issue by bstaletic** [MightyCreak/mesamatrix#142]
[The commit](https://cgit.freedesktop.org/mesa/mesa/commit/?id=55b68c4833c747c899ea2752182c8fc8e6aeb61b) introduced Vulkan 1.1 section, which isn't present on mesamatrix.net

**Comment by bstaletic** [comment]
Sorry about this. For some reason I didn't see the Vulkan 1.1 section.
Once again, I apologise for the noise (I was expecting Vulkan 1.1 to be below Vulkan 1.0, which would be inconsistent with OpenGL).

**Comment by romainf-unity** [comment]
No worries ;)

FWIW I chose to show the latest versions first (opposite to the order in features.txt) because I think most viewers want first to see where Mesa is now.

**Comment by MightyCreak** [comment]
No worries ;)

FWIW I chose to show the latest versions first (opposite to the order in features.txt) because I think most viewers want first to see where Mesa is now.
