### ISSUE TITLE
remove all win32 based extensions 

### ISSUE THREAD

**Issue by maxichan** [MightyCreak/mesamatrix#145]
Mesa is non Windows driver/subsystem so it is not necessary to include win32 or dead mir extensions, that only expands quantity of unsupported opengl / vulkan features.

**Comment by MightyCreak** [comment]
I prefer not to remove extensions from the original `features.txt` file. If the devs thought it was relevant to list it, I guess there's a good reason for it (maybe one day it'll work on windows, who knows?).
