### ISSUE TITLE
New OpenGL ES extension special cases

### ISSUE THREAD

**Issue by bstaletic** [MightyCreak/mesamatrix#146]
- `GL_EXT_sRGB_write_control` says `DONE (all drivers that support GLES 3.0+)`
- `GL_EXT_texture_sRGB_R8` says `Done (all drivers that support GLES 3.0+)`

There are two problems: `Done` is not `DONE` and `(all drivers that support GLES 3.0+)` doesn't list the actual drivers. For what it's worth, drivers that support GLES 3.0 are: radeonsi, i965 (with GLES 3.1 supported only by gen7+), nvc0, r600, virgl and freedreno. That is according to mesamatrix itself.

This really looks like mesa devs are being lazy.

**Comment by MightyCreak** [comment]
It's an issue that has to be fixed upstream (the text format in features.txt is too weak and I'm afraid enabling case-insensitivity would break something). If someone would like to email them or propose a patch, I'm sure they'll be fine with it.

**Comment by MightyCreak** [comment]
I made the MR on Mesa's GitLab: https://gitlab.freedesktop.org/mesa/mesa/merge_requests/747

Now we wait ;)

**Comment by bstaletic** [comment]
Shouldn't the "all drivers that support GLES3.0" be changed to explicitly list the drivers too?
Otherwise mesamatrix reports red for all drivers.

**Comment by MightyCreak** [comment]
It should work.. I made a rule about that, but I'm concerned about the "+" in the end. Don't know if the parser will be able to catch it. Anyway, this part of the code isn't called until the extension is actually "DONE".

**Comment by bstaletic** [comment]
Your PR landed, the field in the "mesa" column is green, but all drivers are red, even though some should be green.

**Comment by MightyCreak** [comment]
Yep, I've seen this too (actually I've seen that other extensions have the same text and don't work as well).
There are two concerns actually... the "+" in the end, but that will be easy to fix, and the other part is that it says that it needs GLES **3.0** which is a version that doesn't exist in features.txt. This part might need yet another exception in the code -_-"

**Comment by MightyCreak** [comment]
This is issue is too old. Closing it.

**Comment by qwertychouskie** [comment]
Not sure why this was closed (the issue is still valid), but hopefully https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/42432 will finally fix the extensions with `DONE (all drivers that support GLES 3.0+)`, as GLES 3.0 will actually be tracked.  That said, it's possible that fixes on the Mesamatrix side will also be necessary to display the new data properly.
