### ISSUE TITLE
Please list iris driver too

### ISSUE THREAD

**Issue by soig** [MightyCreak/mesamatrix#147]
Hi
Please list iris driver too
There're now 2 intel drivers:
- classic "intel"
- gallium "iris"
So we should list those 2 drivers under "intel" like we list 2 for "nvidia" or "AMD", or 4 for "software"
Thanks

**Comment by MightyCreak** [comment]
Unfortunately I can't do that because the iris driver is not in the original [features.txt](https://cgit.freedesktop.org/mesa/mesa/tree/docs/features.txt) file. It has to be done upstream, by the mesa devs.

**Comment by stefano2734** [comment]
new crocus driver for older hardware with gen 6 to 7.5 begins with Mesa 21.2.
i965 will be obsolete in the next years for gen6+ with sandy bridge and higher. 
Iris is new standard for broadwell and higher.
So i965 is only necessary for very old hardware in near future.
So Iris and crocus in mesamatrix is only a question of time.

**Comment by qwertychouskie** [comment]
Iris is listed in features.txt now, this issue should be re-opened.

**Comment by MightyCreak** [comment]
You're right :wink:

**Comment by FabioPedretti** [comment]
i965 driver was just removed from features.txt, crocus and iris added:
https://cgit.freedesktop.org/mesa/mesa/commit/?id=aa20ea7c5e58508a07964f19cb8570c3113156cb
https://cgit.freedesktop.org/mesa/mesa/commit/?id=125700cf8b87c4ddd6ec881783d0363d996a8b82
https://cgit.freedesktop.org/mesa/mesa/commit/?id=45a0de84912dfbb9290f5b97595ae8a1478b69bd
mesamatrix misses iris and crocus.
