### ISSUE TITLE
Generate the feature list using mesa C code

### ISSUE THREAD

**Issue by MightyCreak** [MightyCreak/mesamatrix#150]
As said by @mirh in his https://github.com/MightyCreak/mesamatrix/pull/149#issuecomment-516082900, it might be possible to scrap the information directly from the mesa C code instead of features.txt.

If possible, it would be nice to generate a formatted text file by running a command with a binary compiled with mesa's code.

The idea would be to call the functions that set the extension flags, like this one for intel: [`intelInitExtensions`](https://github.com/mesa3d/mesa/blob/master/src/mesa/drivers/dri/i965/intel_extensions.c#L37).

Right now, I don't know if it's possible to get all the wanted information this way. It would need more investigation.

**Comment by mirh** [comment]
That would also allow to have per-generation information about extensions.

**Comment by sehraf** [comment]
For the record: there is also [gpuinfo](https://www.gpuinfo.org/)

**Comment by mirh** [comment]
And there's also [glxinfo](https://people.freedesktop.org/~imirkin/glxinfo/). 
They are all tools that run *empirically* on real hardware though, which is quite different than this.

**Comment by sehraf** [comment]
For the record (again): 
[Here](https://bugs.freedesktop.org/show_bug.cgi?id=111478#c4) Rob Clark suggests to use a CI pipeline to run glxinfo to retrieve the driver capabilities.

**Comment by mirh** [comment]
AFAIK the hardware just reports what the driver tells him to. 
I'm not aware of any information other than the model number that you dynamically query. 

It would certainly be easier because you just have to dump information that most of times is already easily pipelined (grep glxinfo, don't you?).. Still it kinda seems to miss the point here.

**Comment by MightyCreak** [comment]
@sehraf as @mirh said, glxinfo will only tell what the machine is currently running. A CI pipeline would work, but AFAIK you would need to have at least as many machines as you have drivers, and probably more if you want to test the GPU generations within these drivers.

Although it sounds like a pretty interesting project to set up, I don't have the resources (both time and money) to do it.

**Comment by sehraf** [comment]
> I'm secretly hoping someone comes up w/ a way to generate features.txt (at least for drivers w/ drm_shim support) by running glxinfo in CI

I have no idea what `drm_shim` is but to me it sounds like this would be independent of hardware/machine.
The advantage of CI is that you can have as many "machines" as you need. Also this would allow to automatically update features.txt with each commit.

**Comment by MightyCreak** [comment]
I've asked the question on [the freedesktop thread](https://bugs.freedesktop.org/show_bug.cgi?id=111478#c6) about what is drm_shim and Rob answered this:
> They are an $LD_PRELOAD'd thing to spoof enough of the kernel uabi to "run" the driver.  Ie. you can't actually do drawing, but it is enough to run shader-db.  And so I think it should be pretty much enough to run glxinfo.

So.. maybe it's doable, but apparently there are only 2 drivers supporting drm-shim for now: boradcom and freedreno. I've asked if there are more.

**Comment by mirh** [comment]
Parsing source code still seems exponentially less wasteful 
(for as much as instead, there is more complexity in the code to write)

**Comment by MightyCreak** [comment]
This is issue is too old. Closing it.
