### ISSUE TITLE
Only include the first line of the commit messages

### ISSUE THREAD

**Issue by vanillajonathan** [MightyCreak/mesamatrix#158]
Only include the first line commit messages to prevent horizontal scrolling.

Example of a commit with a long message:
https://gitlab.freedesktop.org/mesa/mesa/commit/84e707e6f2292dd886b8385fab0ced5122e35876

> docs/features: Update virgl OpenGL 4.5 features
>
> GL_ARB_clip_control and GL_KHR_robustness are now expose in the guest.

Mesamatrix displays this as:
> "docs/features: Update virgl OpenGL 4.5 features GL_ARB_clip_control and GL_KHR_robustness are now expose in the guest."

Also of interest is to investigate the [`text-overflow`](https://css-tricks.com/almanac/properties/t/text-overflow/) CSS property.

**Comment by MightyCreak** [comment]
Partially fixed with #159 and #160. But indeed it should only take the first line.

**Comment by vanillajonathan** [comment]
Maybe something like this:
```php
$lines = explode("\n", $commit_message);
$subject = $lines[0];
```

Can also be written as:
```php
$subject = explode("\n", $commit_message)[0];
```

**Comment by MightyCreak** [comment]
This is issue is too old. Closing it.
