### ISSUE TITLE
Add Zink

### ISSUE THREAD

**Issue by StandaSK** [MightyCreak/mesamatrix#163]
It was recently added to docs/features.txt:
https://gitlab.freedesktop.org/mesa/mesa/commit/f66bf5ba444e95e82401d8f6fd726e5ef17b3db9

**Comment by oscarbg** [comment]
was going to ask the same so +1

**Comment by MightyCreak** [comment]
I'll add that (and I'll see if the layout can hold one more driver :wink: )
