### ISSUE TITLE
No panfrost?

### ISSUE THREAD

**Issue by L-as** [MightyCreak/mesamatrix#165]
Panfrost doesn't seem to be in the matrix

**Comment by sehraf** [comment]
Lima, too but both are not present in features.txt, which is required.

**Comment by MightyCreak** [comment]
As @sehraf said. I can't track drivers that are not listed in features.txt.

As soon as it is in the file, I'll add it, but in the meantime, I'll close this issue 😉

**Comment by alyssarosenzweig** [comment]
Panfrost dev here -- I just added panfrost to docs/features.txt. Results are a bit, ah, optimistic -- for Mali T760/T860, with the gles3 functionality exposed (via `PAN_MESA_DEBUG=gles3` - I expect that to become default by the end of the month, just need to catch up on some bug fixing). But it should be enough to get some pretty visuals going :)
