### ISSUE TITLE
OpenCL features support

### ISSUE THREAD

**Issue by huwdp** [MightyCreak/mesamatrix#167]
Just an FYI, it looks like OpenCL features might end up in features.txt and it would be good for Mesa Matrix to display them. Reference: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/4979

Thanks for building and maintaining Mesa Matrix! 😀 I refresh the page often and have even made something similar for Flash players myself although it's work in progress.

**Comment by MightyCreak** [comment]
Thanks for the heads up!
I'll follow this MR!

**Comment by pierremoreau** [comment]
The MR has now been merged.

**Comment by MightyCreak** [comment]
Thank you! That will need a bit more changes than adding a new driver. I'll get to it as soon as I can (but I got a lot on my plate at the moment)

**Comment by MightyCreak** [comment]
Well.. I took the time (it was actually faster than anticipated).
I was able to add the OpenCL versions and the "extra" generic extensions, but not the NVIDIA specific extension (there are some other sections like that in the file.. I need to find a way to show that in a better way).

If you want to take a look: https://github.com/MightyCreak/mesamatrix/pull/187

**Comment by pierremoreau** [comment]
Thank you for this quick turnaround!

The MR looks good, and I wouldn’t worry about that other section.

**Comment by huwdp** [comment]
This is awesome! Thank you everyone!

**Comment by MightyCreak** [comment]
> The MR looks good, and I wouldn’t worry about that other section.

Eventually I was able to add the vendor specific section: https://github.com/MightyCreak/mesamatrix/pull/188 (it's merged)
