### ISSUE TITLE
Mesa upstream branch changed to main

### ISSUE THREAD

**Issue by jljusten** [MightyCreak/mesamatrix#196]
I see some changes will be needed, but I'm not sure how extensive. For example, the docs/features.txt link on the main page goes to the old branch. 

https://gitlab.freedesktop.org/mesa/mesa/-/commit/a1c56b80915a1105c5a62aa6ff3ac71c1edd143d

**Comment by sehraf** [comment]
Search turns up 5 [files](https://github.com/MightyCreak/mesamatrix/search?q=master)
