### ISSUE TITLE
Opencl: some features are optional like  images, but there are needed in tables for full support?

### ISSUE THREAD

**Issue by stefano2734** [MightyCreak/mesamatrix#200]
so now no driver has in this tables full opencl 1.0 to 1.2 support.

Other sources say that opencl 1.0 to 1.2 is full supported by Mesa with amd and Nvidia drivers, only optional images and printf are not done or wip.

Some image formats are important but optional, in 1.2 spec none of them are standard
see 
https://www.khronos.org/files/opencl-quick-reference-card.pdf 
https://www.khronos.org/files/opencl-1-1-quick-reference-card.pdf 
https://www.khronos.org/files/opencl-1-2-quick-reference-card.pdf (page 3)

Double and half precision are also optional in opencl 1.0 and 1.1.
So tables of the optional 1.x features are perhaps necessary for full consistency.

The target of full support of all optional features is ok.

Good work.

**Comment by MightyCreak** [comment]
This seems very true, but I think you should open an issue directly on the Mesa repository: https://gitlab.freedesktop.org/mesa/mesa/-/issues

Because I can't do much myself, I'm only following the contents of the features.txt file.

I'll close this issue, but please post the link of the newly created issue here if you want.

**Comment by stefano2734** [comment]
For freedesktop I need an account only for this issue.
Can you please do this issue to Mesa, when you have an account?

the Same issue is also for OpenCL 2.x and 3.0 tables.
So 2 tables at each OpenCL standard, one for duty and one for optional but also important.

**Comment by MightyCreak** [comment]
Done here: https://gitlab.freedesktop.org/mesa/mesa/-/issues/5160

**Comment by stefano2734** [comment]
There is also Open Source Image support in ROCm available since ROCm 3.7.0.

so an example code for images in amd hardware  is now available.

https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/issues/59
https://www.phoronix.com/scan.php?page=news_item&px=ROCm-3.7-OpenCL-Image

But there is no public progress for optional images in Mesa clover amd Module.
