### ISSUE TITLE
Make a better log system

### ISSUE THREAD

**Issue by MightyCreak** [MightyCreak/mesamatrix#21]
Right now "logging" is done using the "debug" property in the config.php file. Of course, debug texts are disabled on the production server, so in the end we don't know if something goes wrong.

A better system would be to "log", instead of "debug", with different categories (the classics "error", "warning", "message"), right into a log file, and also the possibility to display these messages on the website for easier debugging.

**Comment by MightyCreak** [comment]
The recently added Symfony Console and Process libraries already improve the result. We still need to log everything in a file in order to see the commands history and understand what might have gone wrong.

**Comment by Xenopathic** [comment]
I was planning on introducing Monolog support, so we have one unified logging mechanism that can be used both in HTTP code and in CLI code. Monolog works best with Composer though, so I did that first :smile:

**Comment by MightyCreak** [comment]
:+1:

**Comment by Xenopathic** [comment]
Wait, this has been fixed. Forgot to link it in the PR though! #37

**Comment by MightyCreak** [comment]
I'll close it once PR #38 is merged too, which I'll do very soon.
