### ISSUE TITLE
mesamatrix.net certificate expired on 2021-11-03

### ISSUE THREAD

**Issue by decathorpe** [MightyCreak/mesamatrix#213]
Due to the site's HSTS policy, the expired certificate can't even be ignored, so the site is unreachable:

![Screenshot from 2021-11-05 12-12-21](https://user-images.githubusercontent.com/12836693/140502153-11b03327-d0ba-4bc5-867e-001601bec70d.png)

**Comment by MightyCreak** [comment]
Damn.. I'll watch that, thanks!

**Comment by MightyCreak** [comment]
Fixed!
Thanks!
