### ISSUE TITLE
Add Crocus instead of i965

### ISSUE THREAD

**Issue by ticotaco72** [MightyCreak/mesamatrix#227]
i965 is retired as of https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/10153

**Comment by MightyCreak** [comment]
The change still didn't happen in `master` and the linked MR doesn't change `features.txt`. So for now I can't do much about it, but yes, I will do the changes as soon as it is made in the features.txt file.

**Comment by FabioPedretti** [comment]
i965 driver was just removed from features.txt, crocus and iris added:
https://cgit.freedesktop.org/mesa/mesa/commit/?id=aa20ea7c5e58508a07964f19cb8570c3113156cb
https://cgit.freedesktop.org/mesa/mesa/commit/?id=125700cf8b87c4ddd6ec881783d0363d996a8b82
https://cgit.freedesktop.org/mesa/mesa/commit/?id=45a0de84912dfbb9290f5b97595ae8a1478b69bd
mesamatrix misses iris and crocus.
