### ISSUE TITLE
Is Flattr still a valid way to donate?

### ISSUE THREAD

**Issue by kparal** [MightyCreak/mesamatrix#228]
Hi, Flattr is no longer mentioned on the Donate page:
https://mesamatrix.net/donate.php

However, for some time I have been subscribed to this Flattr account:
https://flattr.com/@Creak

Can you please confirm whether Flattr is still useful to support this project, or whether my money has been going to /dev/null? And if it is useful, shouldn't it be linked on the Donate page?

Thanks.

**Comment by MightyCreak** [comment]
Hi @kparal !

I do receive your Flattr donations, thank you so much for your contribution!

I removed the Flattr link a while ago because the total amount was very very low and it felt like no one was really using this platform (as of today, I've gathered 4.15 US$ in 4 years).

**Comment by kparal** [comment]
Oh, ok! That makes sense :) Thanks for info.

**Comment by LifeIsStrange** [comment]
@kparal note that an alternative nowadays is github sponsor

**Comment by MightyCreak** [comment]
This repo does have the GitHub sponsor thing, but it generates even less than Flattr :sweat_smile:
