### ISSUE TITLE
ARB_shader_image_load_store not fully required for GLES 3.1 

### ISSUE THREAD

**Issue by infapi00** [MightyCreak/mesamatrix#229]
Right now ARB_shader_image_load_store appears as one of the extensions needed for OpenGL ES 3.1.

But, OpenGL ES 3.1 spec includes almost all the functionality of the ARB_shader_image_load_store extension, except the need for formatless storing.

This affects specifically the v3d (broadcom) drivers, as it doesn't support formatless storing, but it supports the functionality needed for OpenGL ES 3.1. This was found recently, and soon the driver will stop to expose ARB_shader_image_load_store as supported:

* https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/14288

FWIW, not sure how this should be reflected on mesa matrix. Because OpenGL ES 3.1 requires image load/store functionality. Perhaps a custom entry similar to "GS5 Packing/bitfield/conversion functions" or "16 vertex texture image units"?

**Comment by MightyCreak** [comment]
This is issue is too old. Closing it.
