### ISSUE TITLE
VK_KHR_ray_query isn't listed in Mesa matrix

### ISSUE THREAD

**Issue by shmerl** [MightyCreak/mesamatrix#230]
I noticed that VK_KHR_ray_query is missing in the list of extensions.

Extension info: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_ray_query.html

**Comment by MightyCreak** [comment]
Thanks! I'll take a look at that asap 😉

**Comment by shmerl** [comment]
Thanks!

Here is another ray tracing one that seems to be missing [VK_KHR_ray_tracing_pipeline](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_ray_tracing_pipeline.html).

**Comment by MightyCreak** [comment]
Ah, it's actually because the features.txt doesn't have it.

Could you open an issue upstream and link it here afterwards, so I can track when it'll be done?

[Link to new issue on the Mesa repo](https://gitlab.freedesktop.org/mesa/mesa/-/issues/new?issue%5Bmilestone_id%5D=)

**Comment by shmerl** [comment]
Sure!

**Comment by shmerl** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/issues/5901

**Comment by shmerl** [comment]
It's merged, so I'll close this.
