### ISSUE TITLE
Add Dozen Vulkan driver support..

### ISSUE THREAD

**Issue by oscarbg** [MightyCreak/mesamatrix#235]
Dozen is merged and will be in Mesa 22.1 stable..
there are patches which seem to bring support for Vulkan1.1 soon..
might require Mesa starting to document features for Dozen in release notes..

**Comment by sehraf** [comment]
Mesamatrix can only show what is listed in [features.txt](https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/docs/features.txt).
So as long as Dozen is not listed there, it won't be listed here either.

**Comment by oscarbg** [comment]
might better open an mesa issue requesting that,then?

**Comment by oscarbg** [comment]
issue opened:
https://gitlab.freedesktop.org/mesa/mesa/-/issues/6330

**Comment by sehraf** [comment]
might be added via https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/17796
