### ISSUE TITLE
Many new possible extensions for openCL 3.0.11 in difference to first final 3.0.5

### ISSUE THREAD

**Issue by stefano2734** [MightyCreak/mesamatrix#243]
In newest version 3.0.11 possible new extensions 

https://www.khronos.org/registry/OpenCL/
and see 
https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_API.html#_summary_of_changes_from_opencl_3_0

There are about 20 new possible extensions from first level 3.05 to newest 3.0.11.

**Comment by MightyCreak** [comment]
Thank you for contributing this issue. Alas I am not the one who adds new extensions in mesa, this has to be done in the upstream mesa repository: https://gitlab.freedesktop.org/mesa/mesa (more specifically in [features.txt](https://gitlab.freedesktop.org/mesa/mesa/blob/main/docs/features.txt)).

I'll close this issue as I can't do anything about that from Mesamatrix.

Cheers!
