### ISSUE TITLE
Powervr and panvr available with dozen for Vulkan section

### ISSUE THREAD

**Issue by stefano2734** [MightyCreak/mesamatrix#250]
Powervr and panvr available with dozen for Vulkan section.

**Comment by paolo-caroni** [comment]
Panvk, not panvr. But I agree, mesamatrix nees to be implemented.of these 3 drivers tracking.

**Comment by MightyCreak** [comment]
I can see "panvk" in [featuers.txt](https://gitlab.freedesktop.org/mesa/mesa/blob/main/docs/features.txt), but not "powervr".

Not sure which third driver you are referring to, @paolo-caroni ?

**Comment by paolo-caroni** [comment]
powervr vulkan driver is pvr, for example:

  VK_KHR_external_memory                                DONE (anv, lvp, pvr, radv, tu, v3dv, vn)
  VK_KHR_external_memory_capabilities                   DONE (anv, lvp, pvr, radv, tu, v3dv, vn)

**Comment by MightyCreak** [comment]
Ah! thanks! 😉
