### ISSUE TITLE
Add svga3d (vmware) info..

### ISSUE THREAD

**Issue by oscarbg** [MightyCreak/mesamatrix#251]
Hi,
must report to Mesa devs for svga3d features.txt but pointing here also..
https://docs.mesa3d.org/drivers/svga3d.html
https://cgit.freedesktop.org/mesa/mesa/log/src/gallium/drivers/svga
should be capable of OpenGL 4.3 but not clear how past GL4.3 exts supported:
https://cgit.freedesktop.org/mesa/mesa/commit/src/gallium/drivers/svga?id=e6b60c27643fe2a4cee2c414e5cf082542a047a3
svga: enable GL43 on SVGA GL43 capable device

thanks

**Comment by oscarbg** [comment]
just opened a Mesa issue: https://gitlab.freedesktop.org/mesa/mesa/-/issues/7129

**Comment by MightyCreak** [comment]
Thank you!

Can you poke me when the driver appears in features.txt?

**Comment by MightyCreak** [comment]
This is issue is too old. Closing it.

**Comment by mskiptr** [comment]
The [VMware SVGA3D](https://docs.mesa3d.org/drivers/svga3d.html) driver has now been explicitly added to `features.txt`. Currently, it's only a single extension in GL 4.4 (see <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/38854>), but adding it to Mesamatrix can encourage filling in those gaps in the documentation.

Could this be re-opened? I'd like to file a PR, once I get a local testing environment set up. (But feel free to implement it without me – I just don't want to blindly add things that might break stuff.)
