### ISSUE TITLE
Date of support for Broadcom and Intel GLES 3.1 extensions incorrectly updated every day

### ISSUE THREAD

**Issue by fridenmf** [MightyCreak/mesamatrix#255]
The following GLES 3.1 extensions gets their "date supported"-date incorrectly updated each day even if there is no commits or updates in docs/features.txt related to those implementations:

Broadcom d3d:
GL_ARB_shader_image_load_store

Intel i965:
GL_ARB_compute_shader
GL_ARB_framebuffer_no_attachments
GL_ARB_shader_atomic_counters
GL_ARB_shader_image_load_store
GL_ARB_shader_image_size
GL_ARB_shader_storage_buffer_object
GL_ARB_texture_multisample
GL_ARB_texture_storage_multisample

**Comment by MightyCreak** [comment]
This is issue is too old. Closing it.
