### ISSUE TITLE
Display Rusticl on mesamatrix

### ISSUE THREAD

**Issue by norablackcat** [MightyCreak/mesamatrix#269]
Hello! I started the process of adding rusticl to features.txt here: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/23055

There are some unanswered questions for both that merge request there and how this data will be displayed on the site. We don't know if we should remove clover from the docs quite yet because mesa still ships clover as well as rusticl. If it's possible do you think it's possible to display both the rusticl and clover if we decide we want to keep it there for now? 

Also in rusticl all the devices are disabled by default and some features are hidden behind flags so it may be misleading to display the data as is. 

I'm hoping I can work with the devs here to make sure everything displays properly and what not

**Comment by MightyCreak** [comment]
If the mesa devs agrees to add these informations in features.txt, Mesamatrix will be complying and present these data as well.

I think you did a good job with #270  :wink:

**Comment by stefano2734** [comment]
RustiCL is openCL 3.0 conformant with some image and fp64 support for AMD GCN and Intel Gen12 XE.
https://www.phoronix.com/search/Rusticl
https://www.phoronix.com/news/Rusticl-OpenCL-3.0-Conformance
https://www.phoronix.com/news/Rusticl-Darktable-Milestone
https://www.phoronix.com/news/Rusticl-OpenCL-FP64-Doubles
https://www.phoronix.com/news/Rusticl-RadeonSI-CTS-Near
https://www.phoronix.com/news/Mesa-23.1-Released

**Comment by romulasry** [comment]
Now opencl isn't showing up on the mesamatrix site at the time of this post.

**Comment by zboszor** [comment]
> Now opencl isn't showing up on the mesamatrix site at the time of this post.

That's because #270 wasn't merged yet, but the Mesa change was.

**Comment by MightyCreak** [comment]
The MR is now merged, I'm deploying it in mesamatrix.net right now.

**Comment by stefano2734** [comment]
Printf is not in RustiCL but in Clover a feature, see OpenCL 1.2

All drivers in RustiCL like RadeonSI or Intel Iris in table are in shape for OpenCL 3.0 and not only for 1.0.
Some parts of OpenCL 1.x are optional like image support.
intel xe 12 gen is full conformant for OpenCL 3.0.

clover is conformant for OpenCL 1.2.

but Image support is needed for full use with programs like darktable.
Clover is here not usable. RustiCL is compatible with darktable.

All OpenCL 2.x features are only optional for OpenCL 3.0.

**Comment by stefano2734** [comment]
Optional OpenCL features in clover  int64 base and extended atomic are supported 

In RustiCL optional features:  this features are not on table.
