### ISSUE TITLE
Mesa performance graphing

### ISSUE THREAD

**Issue by RobinMcCorkell** [MightyCreak/mesamatrix#27]
Integration with OpenBenchmarking.org would allow us to display statistics about the performance of the various Mesa drivers over time. Unfortunately there doesn't seem to be any way to export data in a machine readable format from there, but perhaps we could work with Phoronix Media to implement something? An XML or JSON based solution would be best.

**Comment by romulasry** [comment]
If you could get a hold of Michael Larabel that would be at least a nice-to-have.

**Comment by MightyCreak** [comment]
This is issue is too old. Closing it.
