### ISSUE TITLE
OpenCL has different column order compared to OpenGL/Vulkan

### ISSUE THREAD

**Issue by LinAGKar** [MightyCreak/mesamatrix#271]
Maybe this is nitpicky, but the OpenCL tables have the columns in a different order compared to OpenGL and Vulkan. The OpenGL and Vulkan tables (merged together) have the columns in the order "Software | Intel | Nvidia | AMD | Qualcomm | Vivante | Broadcom | Apple | Arm | PowerVR | Translation", but for OpenCL, the columns are in the order "AMD | Arm | Intel | Nvidia | Software".

**Comment by norablackcat** [comment]
I'm of the opinion that the Software support for OpenCL isn't really that important so, should be listed last. Don't really care how the other entries are listed though.

**Comment by LinAGKar** [comment]
Software is probably less important than hardware for OpenGL and Vulkan too, it's just a fallback, so maybe then it should be on the right for all categories. Regardless, I would consider consistency to be more important to reduce confusion, and it's not like the column gets in the way when on the left

**Comment by MightyCreak** [comment]
How about agnostic, alphanumerical ordering?

**Comment by LinAGKar** [comment]
I think it's nice having desktop GPUs grouped together, and ARM SoCs grouped together.

**Comment by MightyCreak** [comment]
I changed to an alphanum order of the vendors on Friday (just to try and see how it goes).

We get this:
* Vulkan:
  ![image](https://github.com/MightyCreak/mesamatrix/assets/6382548/ad705c90-e538-4817-af2a-0d2c1f2ecbd1)
* OpenGL(ES):
  ![image](https://github.com/MightyCreak/mesamatrix/assets/6382548/14a03936-8840-40c6-92d5-74bf8dcb3033)
* OpenCL (Rusticl):
  ![image](https://github.com/MightyCreak/mesamatrix/assets/6382548/b0d417c1-b28d-4b92-9c45-b524c5a22dda)
* OpenCL (Clover):
  ![image](https://github.com/MightyCreak/mesamatrix/assets/6382548/3d27b4b0-1142-434f-a468-b70a148f1256)

It's not that bad... might be my developer brain, but somehow I find it easier to search for something. But I'm still very open to suggestions.

**Comment by mskiptr** [comment]
Sorting the vendors alphabetically is great, but I think the "Software" and "Translation" categories should still come after everything else. As it is now, it is very easy to miss Vivante. I had to specifically search for it to actually notice it there!

And when there are several drivers for a given vendor, I believe ordering these chronologically would make the most sense.

**Comment by MightyCreak** [comment]
Closing this issue. I don't think the solution is to change the order, but maybe to allow to filter/show only certain drivers.

Whomever wants to do it is welcome and can reopen this issue.
