### ISSUE TITLE
nvk is merged, missing from Vulkan drivers

### ISSUE THREAD

**Issue by zboszor** [MightyCreak/mesamatrix#285]

**Comment by tuxayo** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/commit/34ea8dfbdd5ee57477489f1285397ff5168b9a71
https://gitlab.freedesktop.org/mesa/mesa/-/commit/2b85ccacf00f74b11c0a243f0579b38c627e90cf
https://gitlab.freedesktop.org/mesa/mesa/-/commit/dadf9d59e6f9e0c4a7a7e84af6eca85efe24476a
