### ISSUE TITLE
`./mesamatrixctl setup` leads to `zsh: ./mesamatrixctl: bad interpreter: /usr/bin/php: no such file or directory`

### ISSUE THREAD

**Issue by JayFoxRox** [MightyCreak/mesamatrix#289]
I got:

```
zsh: ./mesamatrixctl: bad interpreter: /usr/bin/php: no such file or directory
```

While running `./mesamatrixctl setup`.

- OS: macOS.
- Installed php via brew.

**Proposed fix:**
I was able to run it with a `#!/usr/bin/env php` shebang instead.

**Comment by MightyCreak** [comment]
Thanks for your contribution, it's been fixed :wink:
