### ISSUE TITLE
Actual date of the day in 80% of cells of rustiCL 

### ISSUE THREAD

**Issue by stefano2734** [MightyCreak/mesamatrix#301]
Actual date 2024-uv-xy  of the day in 80% of cells of rustiCL 
So development of the last 6 month  is here not available by date.

**Comment by stefano2734** [comment]
I see here today progress or solution.

**Comment by MightyCreak** [comment]
I redeployed and reset the DB from scratch recently. Did it fix the issue?

**Comment by stefano2734** [comment]
My Opinion: Yes, before was at 80% of done cells with actual date. Now only dates of new features done are shown. 
so for me solved.

**Comment by mskiptr** [comment]
It was probably fixed by #305.
