### ISSUE TITLE
virgl opengl version?

### ISSUE THREAD

**Issue by shmerl** [MightyCreak/mesamatrix#312]
What is the actual OpenGL version that virgl supports? For some reason it never shows me 4.6. That's what I see with Mesa 24.2.8 for example:

```
OpenGL renderer string: virgl (AMD Radeon RX 7900 XTX (radeonsi, navi31, LLVM 19.1....)
OpenGL core profile version string: 4.3 (Core Profile) Mesa 24.2.8-1
OpenGL core profile shading language version string: 4.30
OpenGL version string: 4.3 (Compatibility Profile) Mesa 24.2.8-1
```

Am I missing something or why is not 4.6?

**Comment by FireBurn** [comment]
That's probably a question for Mesa rather than here

**Comment by MightyCreak** [comment]
I don't know. Maybe it's the combo (GPU card + virgl driver) that makes it compliant to OpenGL 4.3 only.

I'll close this issue as I really don't know the answer. As @FireBurn said, you could try asking the Mesa devs?

**Comment by stefano2734** [comment]
See 
https://docs.mesa3d.org/drivers/virgl.html
https://gitlab.freedesktop.org/virgl/virglrenderer

actual state here since 5 years.
https://gitlab.freedesktop.org/virgl/virglrenderer/-/blob/main/docs/GL-status.txt?ref_type=heads
