### ISSUE TITLE
Results of Zink in Combination with Vulkan drivers in new table?

### ISSUE THREAD

**Issue by stefano2734** [MightyCreak/mesamatrix#314]
Support in Future of openGL will be often by Zink.

Zink supports complete openGL and OpenGL ES and mostly OpenCL like MESA.

so the Vulkan drivers decides here the level of Open GL support with Zink.

A new Table of this results for developer and user can improve development and usage.
More Users will test the software with more information for developers to bugfix and improvements.

**Comment by MightyCreak** [comment]
Not sure I understand. Zink is an OpenGL driver, which uses Vulkan as a backend.

The Vulkan level doesn't really tell the OpenGL level. OpenGL 4.6 could be achieved with any level of Vulkan. It would be slower as some more advanced extensions in the Vulkan API could help preventing from doing code entirely "in software". 

You can take a look here if you want: <https://docs.mesa3d.org/drivers/zink.html>. You'll see that each version of OpenGL have specific requirements. Take a look at For OpenGL 4.4, you'll see that it can be achieved with Vulkan 1.1 or 1.2, it's just that the required extensions are different.

I'll close this issue as I don't think there is a way to clearly show the link between Zink's compliance and the Vulkan's.

**Comment by mskiptr** [comment]
@MightyCreak I think the point here was to include extra columns in the GL tables that would show which extensions are exposed by Zink on various kinds hardware.

**Comment by stefano2734** [comment]
My point is here: Zink supports full OpenGL 4.6+ with some minimal hardware for all features.
on the other side the Vulkan driver for Zink openGL service must support some features more than Vulkan 1.0.

See https://docs.mesa3d.org/drivers/zink.html

so Intel and amd Vulkan drivers Supports Zink Full in newer hardware.
In older hardware is perhaps limitation.

openGL 4.2+ of Zink needs Vulkan 1.2+ Features.

So my wish is a reverse table of Zink openGL support of Mesa Vulkan drivers.

in future there will be no native openGL drivers for new hardware.
Zink will do openGL 2.1 to 4.6+ with Vulkan drivers 1.0+ to 1.2+.

Actual the support is not full.
A table can document this for more development and perfection.

**Comment by mskiptr** [comment]
@stefano2734 The problem with implementing this is it requires a lot of information (afaik) not present within `features.txt`. So if you want to see such a table within Mesamatrix, you will first need to get Mesa itself to expose this data in some easy to parse way.

**Comment by MightyCreak** [comment]
@mskiptr this, and also the fact that, by the time zink replaces completely OpenGL, a few of the older drivers will be long gone. So, all in all, is it worth the effort?

**Comment by stefano2734** [comment]
> @stefano2734 The problem with implementing this is it requires a lot of information (afaik) not present within `features.txt`. So if you want to see such a table within Mesamatrix, you will first need to get Mesa itself to expose this data in some easy to parse way.

See https://docs.mesa3d.org/drivers/zink.html
Most information is available to support zink with Vulkan:
You can it make difficult with all points in Zink-html 

In first shot it is simpler:
Vulkan 1.2 and some extensions support openGL 2.1 to 4.6
Intel Anvil, AMD RadV, NVIDIA NVK, Broadcom Turnip, Lavapipe and Google Venus support Vulkan 1.3.

so all Hardware with this level will support Zink from OpenGL 2.1 to 4.6.

ARM PanVK, Broadcom v3dv, Microsoft dozen supports only 1.0+. So here is more perfect table with the sub points needed.
Perhaps they support no OpenGL 2.1 or much more to OpenGL 4.x.
But Microsoft supports openGL 4.6+ with d3d12, so it is no actual problem.

OpenGL 2.1: Vulkan 1.0 and some more extensions like vk_KHR_maintenance 
or Vulkan 1.2 with the scalar block feature

OpenGL 3.0: is OpenGL 2.1 support with some more features

At the end: start simple this table: Vulkan 1.3 supports full zink.
Vulkan 1.2 supports  Zink openGL 4.1 and with some features to 4.6.
Vulkan 1.1 supports  Zink openGL 4.1 and with some more features to 4.6.
Vulkan 1.0 supports Zink OpenGL 2.1 and with many more features to 4.6.

so some is simple but perfect is more complicated.
