### ISSUE TITLE
Not compatible with PHP 5.3 anymore

### ISSUE THREAD

**Issue by MightyCreak** [MightyCreak/mesamatrix#32]
Since 8514009c6e499216eb89f910d4719244f3aece3a, Mesamatrix isn't compatible with PHP 5.3, because initialization of `const`'s variables with arithmetical expressions is a feature of PHP 5.6.

**Comment by Xenopathic** [comment]
Perhaps it would be best to change numeric calculations to their evaluated form, with a comment showing how to derive that? So 90 days (used in UrlCache) could be:

    const EXPIRATIONDELAY = 7776000; // = 90 * 24 * 60 * 60 = 90 days
