### ISSUE TITLE
Feature: Mesa mailing list scraping

### ISSUE THREAD

**Issue by Xenopathic** [MightyCreak/mesamatrix#60]
At the moment we only show an extension 'in progress', which doesn't really give much information as to the state of the extension. Patches to implement extensions are sent via the [Mesa mailing list](http://lists.freedesktop.org/mailman/listinfo/mesa-dev), and it might be possible to scrape that mailing list for `PATCH` emails containing the extension name in the subject, and/or `PATCH` emails that change lines in `GL3.txt`. Then we can have two states of 'in progress' - 'in development' and 'in review'.

Rationale for this is that Phoronix scrapes mailing lists, so users are notified of (potential) new extension support as soon as the patches are submitted, so we should show them.

**Comment by MightyCreak** [comment]
I have no idea how to scrape a mailing list, but the challenge is interesting.

My main concern is to know how sure we can be that it is in dev or in review. Is there a format that the devs have to respect when they ask for a review? Or simply that if there is the extension in the subject + a patch in the mail, then it's considered a review?

We could also gather all the mails that talk about the concerned extension and list them. So we could follow the discussions around a specific extension.

Thanks for the feature proposition!

**Comment by Xenopathic** [comment]
Yes, I think that patches are only submitted when a feature is ready for review. It doesn't necessarily mean that the patch set will be accepted, so we might need a 'time-out' of sorts on the 'in review' stage, so that rejected patch sets have the extension status reset to 'in development'. All speculation at this stage :laughing:

It'd be great to link to the patch mails, but for a first implementation I think we should just leverage our tooltip 'footnote' mechanism, with the ability to click on the extension bubble to get to the mail archive page.

**Comment by baka0815** [comment]
You could just display an information about the "last activity on the mailing list"-day.
That "activity" could then be just an RFC.

**Comment by mercuriete** [comment]
Nobody is using mailing lists nowadays.

Other solution is scraping gitlab personal repositories searching for commits on features.txt but the scope will be very very different to the actual issue.

Closing this ticket can be another option.

**Comment by MightyCreak** [comment]
I agree, objectively I'll never implement this. Closing it.

Thanks!
