### ISSUE TITLE
Why GL_ARB_sparse_texture is not mentioned?

### ISSUE THREAD

**Issue by procedural** [MightyCreak/mesamatrix#69]
Or GL_ARB_bindless_texture? I wonder :)

**Comment by MightyCreak** [comment]
Simply because it's not in the [GL3.txt](http://cgit.freedesktop.org/mesa/mesa/plain/docs/GL3.txt) on Mesa's git ;)

I'm not sure why it's not in this file though. Maybe because it's part of another extension? You can ask the mesa devs if you want more insights ;)

**Comment by procedural** [comment]
Ok then, thanks! :)
