### ISSUE TITLE
We were featured on a Phoronix article!

### ISSUE THREAD

**Issue by Xenopathic** [MightyCreak/mesamatrix#71]
http://www.phoronix.com/scan.php?page=news_item&px=Radeon-OGL4-28-July-Features

> Mesa is on the heels of full OpenGL 4.0~4.2 support with the Nouveau Gallium3D driver already advertising OpenGL 4.1 support but that state varies based on the hardware drivers, with Intel and Radeon (R600 and RadeonSI) following close behind as detailed for easy viewing with the MesaMatrix.net.

Personal goal -> achieved :smile:

**Comment by MightyCreak** [comment]
Yep, that's great! And the number of visits exploded the day OpenGL 4.0 was out (from 100 per day to more than 2500!). And right now it's around 600/day :smile: 

We're also on Heise.de: http://www.heise.de/open/meldung/Quelloffene-Linux-3D-Treiber-bekommen-OpenGL-4-0-Unterstuetzung-2760942.html

\o/
