### ISSUE TITLE
OpenGL ES 3.2 is missing

### ISSUE THREAD

**Issue by vanillajonathan** [MightyCreak/mesamatrix#77]
Version 3.2 is missing from the listing.

**Comment by MightyCreak** [comment]
This is because there are no data about this version of OpenGL ES in the source file:  
http://cgit.freedesktop.org/mesa/mesa/tree/docs/GL3.txt

**Comment by vanillajonathan** [comment]
Indeed.

I request OpenGL ES 3.2 to be added to the GL3.txt file.

**Comment by MightyCreak** [comment]
You requested it in the mesa mailing-list? If so, once it's done it should appear automatically in Mesamatrix.

**Comment by vanillajonathan** [comment]
No, I did not put a request on the mailing list.

However this seems to have been fixed two days ago;
http://cgit.freedesktop.org/mesa/mesa/commit/docs/GL3.txt?id=2e7e3fe55f1ff9714e4d83cc9db7cbd36e149da5

**Comment by MightyCreak** [comment]
Yep, I've just seen that (getting back from week end). It should have been parsed, but I suppose the parser is a bit disturbed by the end of the file which is not really standardized.

So it's officially an issue now ;)
