### ISSUE TITLE
OpenGL ES is refered to as OpenGLES

### ISSUE THREAD

**Issue by vanillajonathan** [MightyCreak/mesamatrix#78]
OpenGL ES is incorrectly refereed to as OpenGLES without the space.

**Comment by MightyCreak** [comment]
I'll see what I can do about that ;)

It is how it is wrote in the source file:  
http://cgit.freedesktop.org/mesa/mesa/tree/docs/GL3.txt

**Comment by vanillajonathan** [comment]
I suspected so, but I found no reference to the string "OpenGLES" in the file when I checked.

**Comment by MightyCreak** [comment]
Search for `GLES`, it at the very end of the file ;)

**Comment by vanillajonathan** [comment]
Oh, I guess it is line 205.

**Comment by MightyCreak** [comment]
That's it ;)
