### ISSUE TITLE
Add support for the khronos openGL 2015 specification 

### ISSUE THREAD

**Issue by LifeIsStrange** [MightyCreak/mesamatrix#82]
Here a link for documentation http://www.phoronix.com/scan.php?page=article&item=sig-gles32-glu&num=1

And now Intel support one of these extensions post 4.5

http://phoronix.com/scan.php?page=news_item&px=ARB_shader_clock-Intel
Thanks !

**Comment by MightyCreak** [comment]
I'm afraid I can't do that. If an extension has to be added, it must be done on the source file (GL3.txt) in the Mesa code base (I am merely reflecting its content). You can ask the Mesa devs to add it in their text file and it will automatically get synchronized here.

**Comment by stalkerg** [comment]
The main problem with VC4 in that fact what they support only OpenGL2 by hardware but GL3.txt start tracking driver only from OpenGL3.

**Comment by LifeIsStrange** [comment]
Well a compromise would be to in addition of the GL3.txt, the comunity could easily add the 2015 extensions and other drivers support manually ? 
If @MightyCreak or a contributor add a way for the comunity to add content and that we ask Michael larabel from phoronix to ask some contribution from the linux/free software comunity/distros, both issues should quickly be resolved. :) 
I can manually add the 2015 extensions this summer but I yet don't know where.
