### ISSUE TITLE
Add freedreno/ir3, Raspberry Pi/vc4

### ISSUE THREAD

**Issue by xxmitsu** [MightyCreak/mesamatrix#83]
Please add freedreno/ir3, Raspberry Pi/vc4 as drivers backends, so we can also track progress for those.

Thank you.

**Comment by MightyCreak** [comment]
As for #82, I won't be able to do that. If an extension has to be added, it must be done on the source file (GL3.txt) in the Mesa code base (I am merely reflecting its content). You can ask the Mesa devs to add it in their text file and it will automatically get synchronized here.
