### ISSUE TITLE
Add NVIDIA gfx cards in the decoder ring

### ISSUE THREAD

**Issue by MightyCreak** [MightyCreak/mesamatrix#84]
As mentioned in a [comment of the commit](https://github.com/MightyCreak/mesamatrix/commit/bbc11db1f742a7738fa23e7884bfdd47ea469615#commitcomment-14544179), here is the link to decode the NVIDIA GPUs:

http://nouveau.freedesktop.org/wiki/CodeNames/

**Comment by SethBarberee** [comment]
I can start on this after I finish #123

**Comment by Ruedii** [comment]
I think adding the decoder ring for all cards would be helpful.  

Most notably nVidia and AMD use rather obscure codenames in the mesa feature list.  However, Intel chips are not that clear either.

**Comment by MightyCreak** [comment]
Ah actually I removed the feature as it was too much to maintain realistically.
