### ISSUE TITLE
OpenSWR support?

### ISSUE THREAD

**Issue by AndrewJDR** [MightyCreak/mesamatrix#96]
Now that the OpenSWR software driver has landed in Mesa, could we perhaps get a new 'OpenSWR' Column added to mesamatrix alongside llvmpipe and softpipe?

http://www.phoronix.com/scan.php?page=news_item&px=OpenSWR-Lands-In-Mesa

**Comment by MightyCreak** [comment]
To do that, I need for the Mesa devs to add OpenSWR in GL3.txt.

I don't know yet if they're going to do it.

**Comment by Tele42** [comment]
mesa/swr is now included in gl3.txt.

**Comment by MightyCreak** [comment]
Oh it seems that the parser doesn't like the new driver :smile: 
I'll fix that and add the swr driver at the same time! thnks!

**Comment by prcastro** [comment]
Closed by dfc8e40416e0a083f8bc3318272dcd401b4583a8

**Comment by MightyCreak** [comment]
Yey! Forgot this one! ;)
